name: Package & Test

on:
  push:
    branches-ignore:
      - 'dependabot/*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  package_and_test:
    name: Package and Test
    # Use the "reusable workflow" from the hyperspy organisation
    uses: hyperspy/.github/.github/workflows/package_and_test.yml@main
    with:
      EXTRAS: ''
      ADDITIONAL_TEST_DEPENDENCIES: 'qtconsole jupyterlab pytest'
